const lableText = {
    add: 'Kontakt anlegen:',
    edit: 'Kontakt editieren: #',
    topic: 'Übersicht',
    table: 'Kontakte',
    saveRec: 'Speichern',
    cancel: 'Schließen',
    reset: 'Inhalt',
    valReset: 'Validierung',
    newRec: 'Neu',
    uploadJson: 'Import',
    resetBtn: 'Daten laden',
    searchItem: 'Kontakte filtern',
    requiredField: 'Pflichtfeld',
    counter: 'eingefügte Zeichen',
    del: 'Kontakt löschen: #',
    delRec: 'Löschen',
    delQuestion: 'Wollen Sie den Kontakt wirklich löschen?',
    nameRuleLabel: 'Min 3 Zeichen',
    emailRuleLabel: 'E-mail muss gültig sein',
    zipRuleLabel: 'Min 5 Zahlen',
    selectCols: 'Spalten auswählen',
    clearHint: 'X Standard Einstellung',
    selectHint: 'andere',
    age: ' Jahre',
    born: 'Geburtsdatum',
    alertInfo: 'info',
    alertSuccess: 'success'
  }